### PR TITLE
Fix issue #14 : enables multiple option to download the report

### PR DESCRIPTION
**Pull request by pradnyabhukan**
Included the jspdf library and a custom dropdown button

### CODE REVIEW

**Comment by Siddheshuncodes** [comment]
Please add relevant Screenshots of changes you made

**Comment by pradnyabhukan** [comment]
Sure, here are the screenshots

Screen Shot 2024-11-18 at 10 59 29 PM

Screen Shot 2024-11-18 at 10 59 52 PM

**Review by Siddheshuncodes — APPROVED** [review]
This looks good to me 

we can merge this enhancement.

**Review by divyesh-mali — APPROVED** [review]

**Comment by Siddheshuncodes** [comment]
Thanks for your contribution can we feature you on the contributors page of this Website?
Along with Linkedin and X(Twitter)

We are doing this to give credit to all our awesome contributors.

**Comment by pradnyabhukan** [comment]
Yes, I’d be happy to be featured on the contributors' page.

**Pull request merged**
