### PR TITLE
Merge branch 'main' of https://github.com/Swifty9/Maverick-AI

### PR DESCRIPTION
**Pull request by hrutikkharjul**

### CODE REVIEW

**Comment by Siddheshuncodes** [comment]
Add a screenshot of your change and what you did explain in brief

**Comment by hrutikkharjul** [comment]
issue1

**Comment by hrutikkharjul** [comment]
added the logo and adjusted the width and height of the logos

**Review by Siddheshuncodes — APPROVED** [review]
This works for me looking good to me 
We can merge this

**Pull request merged**
